Have travis install latest bundler
Why you made the change:

I did this in hopes to avoid the `NoMethodError: undefined method `spec'
for nil:NilClass` while using bundler 1.7.6 which is travis default
bundler version.